### ISSUE TITLE
Test on multiple OSes?

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-gitlab#83]
Right now all the tests are run within only Ubuntu 12/14 on Travis CI directly. I'd rather test in clean Docker environments like I do my other roles... but it might be a little tricky since GitLab's installation is rather complicated and kinda convoluted. At least it was _last_ time I attempted this.

**Comment by geerlingguy** [comment]
Running test locally...

**Comment by geerlingguy** [comment]
It looks like `gitlab-ctl reconfigure` hangs when run inside the container. Searching around, it looks like it's getting all kinds of confused since it thinks it's running in a plain docker environment. Traced it back to https://gitlab.com/gitlab-org/omnibus-gitlab/blob/1d335dbba6c038ad71385d424c799b9acdba4f8e/files/gitlab-cookbooks/runit/recipes/default.rb, so I'm going to see if deleting the `/.dockerenv` file helps.

**Comment by geerlingguy** [comment]
Yay, now it seems to be working better...

```
[2017-11-30T17:36:10+00:00] INFO: template[/var/opt/gitlab/.gitconfig] updated file contents /var/opt/gitlab/.gitconfig
[2017-11-30T17:36:10+00:00] INFO: execute[/opt/gitlab/embedded/service/gitlab-shell/bin/gitlab-keys check-permissions] ran successfully
[2017-11-30T17:36:11+00:00] INFO: template[/var/opt/gitlab/gitlab-rails/etc/gitlab.yml] backed up to /opt/gitlab/embedded/cookbooks/cache/backup/var/opt/gitlab/gitlab-rails/etc/gitlab.yml.chef-20171130173611.054720
[2017-11-30T17:36:11+00:00] INFO: template[/var/opt/gitlab/gitlab-rails/etc/gitlab.yml] updated file contents /var/opt/gitlab/gitlab-rails/etc/gitlab.yml
[2017-11-30T17:36:11+00:00] INFO: execute[chown -R root:root /opt/gitlab/embedded/service/gitlab-rails/public] ran successfully
[2017-11-30T17:36:11+00:00] INFO: execute[/opt/gitlab/bin/gitlab-ctl start redis] ran successfully
[2017-11-30T17:36:12+00:00] INFO: execute[/opt/gitlab/bin/gitlab-ctl start postgresql] ran successfully
```

(From `/var/log/gitlab/reconfigure/*` log files).

Doing a little more testing locally.

**Comment by geerlingguy** [comment]
Now getting:

```
[2017-11-30T17:37:04+00:00] ERROR: Running exception handlers
[2017-11-30T17:37:04+00:00] ERROR: Exception handlers complete
[2017-11-30T17:37:04+00:00] FATAL: Stacktrace dumped to /opt/gitlab/embedded/cookbooks/cache/chef-stacktrace.out
[2017-11-30T17:37:04+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-11-30T17:37:04+00:00] ERROR: bash[migrate gitlab-rails database] (gitlab::database_migrations line 51) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of "bash"  "/tmp/chef-script20171130-12920-1rj34oa" ----
STDOUT: rake aborted!
TZInfo::DataSourceNotFound: No source of timezone data could be found.
Please refer to http://tzinfo.github.io/datasourcenotfound for help resolving this error.
/opt/gitlab/embedded/service/gitlab-rails/config/environment.rb:5:in `<top (required)>'
/opt/gitlab/embedded/bin/bundle:23:in `load'
/opt/gitlab/embedded/bin/bundle:23:in `<main>'
TZInfo::ZoneinfoDirectoryNotFound: None of the paths included in TZInfo::ZoneinfoDataSource.search_path are valid zoneinfo directories.
/opt/gitlab/embedded/service/gitlab-rails/config/environment.rb:5:in `<top (required)>'
/opt/gitlab/embedded/bin/bundle:23:in `load'
/opt/gitlab/embedded/bin/bundle:23:in `<main>'
Tasks: TOP => gitlab:db:configure => environment
(See full trace by running task with --trace)
STDERR: 
---- End output of "bash"  "/tmp/chef-script20171130-12920-1rj34oa" ----
Ran "bash"  "/tmp/chef-script20171130-12920-1rj34oa" returned 1
[2017-11-30T17:37:04+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by robbintt** [comment]
Do you normally test on docker? I asked someone at docker about this and
they recommended I use docker with dockerfiles for deployment, not ansible,
but I thought that use case seemed fine. Then I met some other people
testing ansible roles on docker. I test my roles on vagrant now.

**Comment by geerlingguy** [comment]
See: https://gitlab.com/gitlab-org/omnibus-gitlab/issues/2229#note_27448490

Need to add `tzdata` as a required dependency.

**Comment by geerlingguy** [comment]
Also need to run a curl-based test to ensure it's actually responding to web requests.
